version: 2
updates:
  - package-ecosystem: "nuget"
    directory: "/smo-backend"
    schedule:
      interval: "monthly"
    assignees:
      - "GNimrodG"
    commit-message:
      prefix: "[backend-nuget]"
  - package-ecosystem: "docker"
    directory: "/smo-backend"
    schedule:
      interval: "monthly"
    assignees:
      - "GNimrodG"
    commit-message:
      prefix: "[backend-docker]"

  - package-ecosystem: "npm"
    directory: "/smo-frontend"
    schedule:
      interval: "monthly"
    assignees:
      - "GNimrodG"
    commit-message:
      prefix: "[frontend-npm]"
  - package-ecosystem: "docker"
    directory: "/smo-frontend"
    schedule:
      interval: "monthly"
    assignees:
      - "GNimrodG"
    commit-message:
      prefix: "[frontend-docker]"
