FROM node:slim AS build

WORKDIR /app

COPY package.json yarn.lock tsconfig.json ./

RUN yarn install --frozen-lockfile

COPY ./src ./src

RUN yarn build:no-sentry

RUN yarn prisma generate

FROM node:slim AS dependencies

WORKDIR /app

COPY ./package.json ./yarn.lock ./

ENV NODE_ENV=production

RUN yarn install --frozen-lockfile --production

RUN yarn prisma generate

FROM node:slim  AS base

RUN apt update && apt install -y curl && rm -rf /var/lib/apt/lists/*

FROM base AS release

WORKDIR /app

ENV NODE_ENV=production

COPY --from=build /app/dist ./dist
COPY --from=dependencies /app/node_modules ./node_modules
COPY ./package.json ./yarn.lock ./
COPY ./prisma ./prisma

RUN yarn prisma generate

EXPOSE 3000

HEALTHCHECK --interval=30s --timeout=30s --start-period=5s --retries=3 CMD curl --fail http://localhost:3000/status || exit 1

VOLUME /app/data

CMD ["yarn", "prod:migrate"]
