services:
  web:
    build: .
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=Host=db;Port=5432;Database=smo;Username=smo;Password=smo
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./bin/docker-data:/app/data
    healthcheck:
      test: [ "CMD-SHELL", "/usr/bin/curl -f http://localhost:3000/health || exit 1" ]
      interval: 10s
      timeout: 5s
      retries: 3
  db:
    image: postgis/postgis:16-3.4
    environment:
      POSTGRES_USER: smo
      POSTGRES_PASSWORD: smo
      POSTGRES_DB: smo
    expose:
      - 5432
    ports:
      - "5432:5432"
    healthcheck:
      test: "PGPASSWORD=smo pg_isready -h 127.0.0.1 -U smo -d smo"
      interval: 5s
      start_interval: 10s
