FROM node:slim AS build

WORKDIR /app

COPY package.json yarn.lock tsconfig.json ./

RUN yarn install --frozen-lockfile

COPY ./src ./src

RUN yarn build

FROM node:slim AS dependencies

WORKDIR /app

COPY ./package.json ./yarn.lock ./

ENV NODE_ENV=production

RUN yarn install --frozen-lockfile --production

FROM node:slim AS release

WORKDIR /app

ENV NODE_ENV=production

COPY --from=build /app/dist ./dist
COPY --from=dependencies /app/node_modules ./node_modules

EXPOSE 3000

RUN apt update && apt install -y curl && rm -rf /var/lib/apt/lists/*

HEALTHCHECK --interval=30s --timeout=30s --start-period=5s --retries=3 CMD curl --fail http://localhost:3000/status || exit 1

VOLUME /app/data

CMD ["node", "dist/index.js"]
