FROM mcr.microsoft.com/dotnet/aspnet:10.0 AS base

ARG APP_UID=1000

RUN apt-get update && \
    apt-get install -y curl && \
    rm -rf /var/lib/apt/lists/* /var/cache/apt/* && \
    chmod +rx /usr/bin/curl

USER $APP_UID
WORKDIR /app
EXPOSE 3000

FROM mcr.microsoft.com/dotnet/sdk:10.0 AS build
ARG BUILD_CONFIGURATION=Release
WORKDIR /src
COPY ["./smo-backend.csproj", "./"]
RUN dotnet restore "./smo-backend.csproj"
COPY . .
WORKDIR "/src"
RUN dotnet build "smo-backend.csproj" -c $BUILD_CONFIGURATION -o /app/build

FROM build AS publish
ARG BUILD_CONFIGURATION=Release
RUN dotnet publish "smo-backend.csproj" -c $BUILD_CONFIGURATION -o /app/publish /p:UseAppHost=false

FROM base AS final

WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "smo-backend.dll"]
